### ISSUE TITLE
Practica 5: Reconocimiento de patrón Hiro  

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-jaciel#1]
[Practica 5 - Reconocimiento de patrón Hiro.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-jaciel/files/8601134/Practica.5.-.Reconocimiento.de.patron.Hiro.pdf)

**Comment by Brendalp** [comment]
Calificación = 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
